# Use an official Python runtime as a parent image
FROM ubuntu

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Define environment variable
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV PATH="/root/miniconda3/bin:${PATH}"

# Install any needed packages specified in requirements.txt
RUN chmod +x Miniconda3-latest-Linux-x86_64.sh && \
    ./Miniconda3-latest-Linux-x86_64.sh -b && \
    yes | pip install mlflow

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["mlflow", "server", "--default-artifact-root", "wasbs://mlflow@<AZURE BLOB NAME>.blob.core.windows.net/", "--host", "0.0.0.0"] 
